# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:50:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Format(Enum):
    swagger10 = 'swagger10'
    swagger20 = 'swagger20'
    swaggeryaml = 'swaggeryaml'
    apiblueprint = 'apiblueprint'
    wadl2009 = 'wadl2009'
    raml = 'raml'
    apimatic = 'apimatic'


class TransformPostRequest(BaseModel):
    url: Optional[str] = None


class TransformPostResponse(BaseModel):
    pass
